name: swype_kids
description: Výuková hra pro děti – učíme se písmenka swyp tahem po klávesnici.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Bold.ttf
          weight: 700
        - asset: fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: fonts/Nunito-Black.ttf
          weight: 900
