name: swype_kids
description: Výuková hra pro děti – učíme se písmenka swyp tahem po klávesnici.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

flutter:
  uses-material-design: true
